### ISSUE TITLE
Classes do not comply with PSR-4

### ISSUE THREAD

**Issue by khamyl** [Bacon/BaconQrCode#101]
The installation

`composer require libern/qr-code-reader`

yields 

`Class Zxing\Common\AbstractEnum located in .../www/vendor/libern/qr-code-reader/src/lib\common\AbstractEnum.php does not comply with psr-4 autoloading standard. Skipping.`

Errors for each Zxing class

**Comment by DASPRiD** [comment]
This is not the `Zxing` project.

**Comment by khamyl** [comment]
:D I know.. as you can see I was trying to install `libern/qr-code-reader` not Zxing.

**Comment by DASPRiD** [comment]
That's not this project either.

**Comment by khamyl** [comment]
Oh, sorry :/
