### ISSUE TITLE
possible infection in "Modules.php" file

### ISSUE THREAD

**Issue by Kali-Gula** [Bacon/BaconQrCode#109]
Hello, I would like to ask if in your source code there is a file called "Modules.php"
A colleague tells me that on his website, passing wordfence, a path appears: "wp-content / mu-plugins / nue / vendor / bacon / bacon-qr-code / Modules.php" detected as malware.

I have downloaded your .zip and I don't see that it has that file.
This installation is normal in mu-plugins / nue

Thansk

**Comment by DASPRiD** [comment]
BQC v1 had a `Module.php`, but no `Modules.php`:
https://github.com/Bacon/BaconQrCode/blob/1.0.3/Module.php

**Comment by Kali-Gula** [comment]
Ok, I'll delete the file then.
Do you want me to send you a .zip with the infected plugin for you to review? I say it because it goes like your name and developer.
Thanks

**Comment by DASPRiD** [comment]
You could put the source code in a gist and link it here, sure.

**Comment by Kali-Gula** [comment]
I don't know how to do it.
If you explain maybe

**Comment by DASPRiD** [comment]
Just go to https://gist.github.com/, there you can paste the source of that file.

**Comment by Kali-Gula** [comment]
[vendor.zip](https://github.com/Bacon/BaconQrCode/files/8511504/vendor.zip)
I don't know if it's ok here

**Comment by DASPRiD** [comment]
Yeah, that's definitely malware.

**Comment by Kali-Gula** [comment]
OK, THANKS
its inside "wp-content/mu-plugins". Called "nue"... Can you know where it comes from ? or how install it ?
[nue.zip](https://github.com/Bacon/BaconQrCode/files/8511539/nue.zip)
Do you think I can DELETE all the mu-plugin directory if I don't use it.

**Comment by DASPRiD** [comment]
I have no idea.

**Comment by Kali-Gula** [comment]
OK, Really THANKS ! ;)
