### ISSUE TITLE
PHP 8.1: Implicit conversion from float 26.666666666666664 to int loses precision

### ISSUE THREAD

**Issue by cscrewsandcaptains** [Bacon/BaconQrCode#110]
public static function getDataMaskBit($maskPattern, $x, $y)
    {
        ...
            case 4:
                $intermediate = (BitUtils::unsignedRightShift($y, 1) + ($x / 3)) & 0x1;
                
the term  $x / 3 must not be an integer.
Can you please round the term?

**Comment by rafaelmiti** [comment]
I forked the project to create a pr but realized that the fix is already on master. It's just a matter of tagging and pushing the tag.

![Screenshot 2022-05-12 171223](https://user-images.githubusercontent.com/6079888/168160148-cb1eed33-0407-4af0-84dd-e5efc546f153.png)

**Comment by DASPRiD** [comment]
That is already in 2.0.7. In fact, that change was released 11 months ago.

**Comment by rafaelmiti** [comment]
Yeah, so the problem is really in "2amigos/qrcode-library" that locking this project in ~1.1. Thanks!

**Comment by cscrewsandcaptains** [comment]
oh sorry, rafaelmiti is right the library "2amigos/qrcode-library" is the problem. This library seems to be outdated (last release 2 years ago) (I now use: https://github.com/chillerlan/php-qrcode)
