### ISSUE TITLE
Quick Reference

### ISSUE THREAD

**Issue by anotherZero** [Bacon/BaconQrCode#12]
Might it be possible to at least get a quick list of available methods in this library?

For example: I was unable to figure out how to increase the error correction level, although I saw many references to it throughout the library.  I was able to take the example in the readme and stream the output by changing the $writer->writeFile to $writer->writeString, but the rest is a little difficult to determine without a lot of guesswork... at least for those of us that haven't earned our OOP merit badges yet.

Thanks!

**Comment by SaifurRahmanMohsin** [comment]
I too had to figure it out
+1

**Comment by DASPRiD** [comment]
Well, the EC-level is simply the last parameter of the writeString and writeFile methods:

https://github.com/Bacon/BaconQrCode/blob/master/src/BaconQrCode/Writer.php#L101

Feel free to write a PR to the readme.
