### ISSUE TITLE
Want to add new Eye and QRcode styles - Not an issue looking for optimal suggestions

### ISSUE THREAD

**Issue by hafizSiddiq7675** [Bacon/BaconQrCode#120]
I am looking to add a new QR Code style which will look like the following

<img width="602" alt="image" src="https://user-images.githubusercontent.com/29893550/206417804-1a56ea50-e996-4e31-9f1c-5633ebca5bda.png">

Users will only be able to update the inner color of the eye.

Full Description of the new required designs is described in the following screenshot

<img width="586" alt="image" src="https://user-images.githubusercontent.com/29893550/206418164-0dd06b75-2cbd-4ea4-96e9-18fa19a5b1bd.png">

I am looking for an optimal way to achieve this task.

Thanks in advance

**Comment by hafizSiddiq7675** [comment]
@DASPRiD Thanks for your response, what about the styles, i am looking for any suggestions regarding this.

**Comment by hafizSiddiq7675** [comment]
> The `EyeFill` renderer style already allows you to set separate internal and external colors.
> 
> As for logos, at the moment BaconQrCode does not support that. I remember an older feature request for that, which was abandoned. What you could do at the moment is render the QR code out normally as SVG or PNG, and then update the result by overlaying it with a white square and optionally the logo.

Right now the problem is I am not sure how to render that particular style.

**Comment by DASPRiD** [comment]
Which style exactly are you referring to?

**Comment by hafizSiddiq7675** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/29893550/206513286-c8f88a9f-9d7e-43d4-91ed-0c169fa4a153.png">

@DASPRiD take a look at this image. I am not sure how I can generate the same type of image

**Comment by hafizSiddiq7675** [comment]
yes, I am referring to the bits, having a different style

**Comment by DASPRiD** [comment]
In that case you have to create a Module renderer implenting the [`ModuleInterface`](https://github.com/Bacon/BaconQrCode/blob/master/src/Renderer/Module/ModuleInterface.php).  You should be able to copy the [`SquareModule`](https://github.com/Bacon/BaconQrCode/blob/master/src/Renderer/Module/SquareModule.php) and adjust the path points by a fraction of a pixel.

**Comment by hafizSiddiq7675** [comment]
Thanks for the help, can you give me some suggestions? regarding how to achieve this kind of pattern in SVG?

**Comment by DASPRiD** [comment]
Well, you want the to-left corner of a module to be around +0.05 and the bottom left corner to be around -0.05 on X an Y.

**Comment by hafizSiddiq7675** [comment]
I am sorry, I am not getting it, could you explain more please?

**Comment by DASPRiD** [comment]
I don't have the time to write down complete code for you. I'd suggest to take this to StackOverflow.

**Comment by hafizSiddiq7675** [comment]
thank you
