### ISSUE TITLE
Suggestion: add php gd to composer requirements

### ISSUE THREAD

**Issue by fabiopaiva** [Bacon/BaconQrCode#14]
i try to use without install php gd and get this error:
PHP Fatal error:  Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor() in /tmp/composer-project/vendor/bacon/bacon-qr-code/src/BaconQrCode/Renderer/Image/Png.php on line 42

i suggest to add this requirements to composer.json

**Comment by DASPRiD** [comment]
It's in the suggest section, since we have renderers which don't require php-gd.

**Comment by fabiopaiva** [comment]
How to do without php-gd? I can't find documentation.

**Comment by DASPRiD** [comment]
We have a Text/HTML Renderer

**Comment by nebkam** [comment]
I agree with your reasoning @DASPRiD but then the example in the README is a bit misleading, can we mention that it requires `php-gd`?
