### ISSUE TITLE
BUG? on this line $j is always 0, isn't this meant to be $i ? or actually 0?

### ISSUE THREAD

**Issue by alien999999999** [Bacon/BaconQrCode#147]
https://github.com/Bacon/BaconQrCode/blob/8eba389da071f396d71ddf034289093b9e4e9cae/src/Common/ReedSolomonCodec.php#L176C38-L176C38

**Comment by DASPRiD** [comment]
Actually, this is correct by accident:
https://github.com/quiet/libfec/blob/master/init_rs.h#L99

Feel free to PR a replacement to `0` ;)

**Comment by alien999999999** [comment]
yeah, after looking at the code some more, i got to the same conclusion that it is meant to be 0
