### ISSUE TITLE
Possible bug with non-centered EPS code

### ISSUE THREAD

**Issue by jambajuice2015** [Bacon/BaconQrCode#15]
Thank you for this great QR code encoder.

When generating EPS images the QR code is not centered vertically but the top margin/padding is too small.
A small change in bacon\bacon-qr-code\src\BaconQrCode\Renderer\Image\Eps.php seems to fix that.

Function drawBlock:

from
$this->eps .= ($x . " " . ($this->finalHeight - $y) . " " . $this->blockSize . " " . $this->blockSize . " F\n";

to:        
$this->eps .= $x . " " . ($this->finalHeight - $y - $this->blockSize) . " " . $this->blockSize . " " . $this->blockSize . " F\n";

Thanks again for your effort

**Comment by DASPRiD** [comment]
Can you attach the generated EPS file for showcasing the problem?

**Comment by DASPRiD** [comment]
Fixed by #22
