### ISSUE TITLE
not support muti-bytes-char,such as cjk(china,japan,korea)

### ISSUE THREAD

**Issue by netmou** [Bacon/BaconQrCode#16]
source:
<?php
include "autoload_register.php";
$renderer = new \BaconQrCode\Renderer\Image\Png();
$renderer->setHeight(256);
$renderer->setWidth(256);
$writer = new \BaconQrCode\Writer($renderer);
$writer->writeFile('http://www.baidu.com?keywords=汉字', 'qrcode.png');
?>

output:

PHP Fatal error:  Uncaught BaconQrCode\Exception\WriterException: Could not encode content to ISO-8859-1 in E:\~tmp\test\src\BaconQrCode\Encoder\Encoder.php:628
Stack trace:
#0 E:\~tmp\test\src\BaconQrCode\Encoder\Encoder.php(539): BaconQrCode\Encoder\Encoder::append8BitBytes('http://www.baid...', Object(BaconQrCode\Common\BitArray), 'ISO-8859-1')
#1 E:\~tmp\test\src\BaconQrCode\Encoder\Encoder.php(86): BaconQrCode\Encoder\Encoder::appendBytes('http://www.baid...', Object(BaconQrCode\Common\Mode), Object(BaconQrCode\Common\BitArray), 'ISO-8859-1')
#2 E:\~tmp\test\src\BaconQrCode\Writer.php(82): BaconQrCode\Encoder\Encoder::encode('http://www.baid...', Object(BaconQrCode\Common\ErrorCorrectionLevel), 'ISO-8859-1')
#3 E:\~tmp\test\src\BaconQrCode\Writer.php(103): BaconQrCode\Writer->writeString('http://www.baid...', 'ISO-8859-1', 1)
#4 E:\~tmp\test\index.php(7): BaconQrCode\Writer->writeFile('http://www.baid...', 'qrcode.png')
#5 {main}
  thrown in E:\~tmp\test\src\BaconQrCode\Encoder\Encoder.php on line 628

**Comment by netmou** [comment]
i change the const var "DEFAULT_BYTE_MODE_ECODING"  from" ISO-8859-1" to "utf-8" in src\BaconQrCode\Encoder\Encoder.php,then every thing is ok

**Comment by DASPRiD** [comment]
You can pass the encoding as third parameter to the ```writeFile()``` method. By the way, for Kanjii, SHIFT-JIS encoding may be more savy on the bytes.

**Comment by netmou** [comment]
set the default encoding with utf8  like better
