### ISSUE TITLE
Background is mandatory? Transparent backgrounds not possible?

### ISSUE THREAD

**Issue by holtkamp** [Bacon/BaconQrCode#18]
When looking at the source code, it seems that a background is always added. 

When looking on how to set a 'transparent' color as background color, I got stuck. It seems the `Gray`, `Rgb` and `Cmyk` do not support transparancy / alpha channel?

**Comment by SimplyCorey** [comment]
@DASPRiD I have had quite a few users ask about this down stream as well.  I looked over #10 and I agree that the background color should be white by default.  If I go ahead and make a pull request with the requested change, can we get this merged in?

Thanks :)

**Comment by DASPRiD** [comment]
I guess so. I'd say that we could alternatively offer RGBA as a color (at least for the outputs, which supports it. I'm not sure whether CMYKA would make any sense, would have to think about that.

**Comment by SimplyCorey** [comment]
RGBA sounds like a better approach.  EPS, PNG, would be able to support alpha channels.  SVG may be able to through the use of `fill-opacity`?

**Comment by DASPRiD** [comment]
SVG supports ```style="fill: rgba();"``` just fine.

**Comment by DASPRiD** [comment]
But as said, Gray and CMYK would have to allow alpha channels as well for consistency.
