### ISSUE TITLE
Max length for string

### ISSUE THREAD

**Issue by llioor** [Bacon/BaconQrCode#21]
Hello,
What is the maximum length size of a generated string?
Do we have relation between "string length" to "size()" function?
Do we have relation between "string length" to "errorCorrection('****Change to Char***')"?

10xxxx, Lior :)

**Comment by llioor** [comment]
is it "Alphanumeric	4,296" from WIKI https://en.wikipedia.org/wiki/QR_code#Error_correction

**Comment by DASPRiD** [comment]
Yes, it depends on the encoding. How is this an issue?

**Comment by llioor** [comment]
Hi @DASPRiD 
I'm generating a URL with parameters.. I'd like to understand how can I verify if the length of the string (URL) will be validate for an 'L' error correction.
What is the method to calculate if the sting is validate?
Thank you very much.

**Comment by DASPRiD** [comment]
Well, that depends. If you don't want to do heavy checks, the easiest way would be to verify that your string does not exceed 2953 bytes (simple `strlen()` check). That check would be valid for any single- or multibyte encoding.

But as you said, you are building URLs. If you URL-encode all parameters properly, they **should** all be in the alphanumeric space. In that case, it is enough to to a `strlen()` check against the said 4296 characters.

**Comment by llioor** [comment]
Ben Thank you very much!!!! perfect answer!
