### ISSUE TITLE
quiet_zone=0 not working

### ISSUE THREAD

**Issue by ThomasLandauer** [Bacon/BaconQrCode#27]
Please make it possible to remove the white border/padding inside the image completely.  
In endroid/QrCode this setting is called `quiet_zone`. I originally raised the issue there https://github.com/endroid/QrCode/issues/95

**Comment by DASPRiD** [comment]
We just had an issue open for that a few days ago, please read the comments on https://github.com/Bacon/BaconQrCode/issues/26.

**Comment by ThomasLandauer** [comment]
Thanks! I didn't look through closed issues ;-)
