### ISSUE TITLE
ErrorCorrectionLevel H issue

### ISSUE THREAD

**Issue by endroid** [Bacon/BaconQrCode#28]
Hi @DASPRiD,

When I generate a QR Code as follows I get a valid image.

$renderer = new \BaconQrCode\Renderer\Image\Png();
        $renderer->setHeight(256);
        $renderer->setWidth(256);
        $writer = new \BaconQrCode\Writer($renderer);
        $writer->writeFile('localhost/preinscription/1/f3a450d9545685097a486e7446730d9f/', 'qrcode.png', Encoder::DEFAULT_BYTE_MODE_ECODING, ErrorCorrectionLevel::L);

However when I increase the error correction level to ErrorCorrectionLebel::H I end up with an image that both my automated reader and my Android Barcode Scanner cannot read. Do you have any idea what could be the issue?

Thanks!

**Comment by endroid** [comment]
Hi @DASPRiD any time to look at this issue? I have another case for you to reproduce this issue and users find it strange that the error correction needs to be set from high to low to get a more reliable QR code.

$renderer = new \BaconQrCode\Renderer\Image\Png();
$renderer->setHeight(300);
$renderer->setWidth(300);
$writer = new \BaconQrCode\Writer($renderer);
$writer->writeFile('http://www.baidu.com/?code=abcxxxxabc&name=yiming&source=tt', 'qrcode.png', Encoder::DEFAULT_BYTE_MODE_ECODING, ErrorCorrectionLevel::H);

**Comment by DASPRiD** [comment]
Sorry, kinda forgot about this issue because I was reading on while on vacation. Will take a look at this week.

**Comment by Dagefoerde** [comment]
Hi, we are having the same issue, at least for some URLs. For reference:
Encoded URL that works: http://localhost/prod33/course/view.php?id=2
Encoded URLs that don't work: https://xsso.uni-muenster.de/LearnWeb/learnweb2/course/view.php?id=24744, https://www.uni-muenster.de/LearnWeb/learnweb2/course/view.php?id=24744

As a workaround we resort to `ErrorCorrectionLevel::QUARTILE` temporarily.

**Comment by DASPRiD** [comment]
@endroid @Dagefoerde I'm unable to reproduce the errors you encounter. On dev-master, they produce QR codes which I can scan with my smartphone and get the correct values back. I'm not tagging 1.0.2 anyway though, since 1.0.1 is a little behind. Please check again if you have any issues with the most recent version. Otherwise I will need more information.

**Comment by endroid** [comment]
Thanks for checking. Are you sure you replaced the error correction in the example with H?
When I install dev-master, create a script with exactly the following code

use BaconQrCode\Encoder\Encoder;
use BaconQrCode\Common\ErrorCorrectionLevel;

$renderer = new \BaconQrCode\Renderer\Image\Png();
$renderer->setHeight(300);
$renderer->setWidth(300);
$writer = new \BaconQrCode\Writer($renderer);
$writer->writeFile('http://www.baidu.com/?code=abcxxxxabc&name=yiming&source=tt', 'qrcode.png', Encoder::DEFAULT_BYTE_MODE_ECODING, ErrorCorrectionLevel::H);

I get the following result.

![qrcode](https://user-images.githubusercontent.com/537253/31631014-ad7eb858-b2b8-11e7-9f31-43e43cff0a6b.png)

Se now the question is: are you able to scan this image or do you get a different one?

**Comment by DASPRiD** [comment]
Oh, apparently it was a little late yesterday and I missed the part about `H`, sorry. Will test again. You are right, I'm unable to scan that code.

**Comment by Dagefoerde** [comment]
Sorry, I also forgot to write above that we are also encountering that problem with `ErrorCorrectionLevel::H`. Switched to `::QUARTILE` as a workaround that works, but I guess `::H` would be better. Thanks for looking into it! :)

**Comment by DASPRiD** [comment]
Problem solved and tagged as 1.0.3. Version 7 (which your QR codes resulted in) was missing the last EcBlock definition.

**Comment by endroid** [comment]
I see they are rendered correctly now. Nice, thank you!
