### ISSUE TITLE
Release v1.0.2 please

### ISSUE THREAD

**Issue by arteniioleg** [Bacon/BaconQrCode#34]
```
composer require bacon/bacon-qr-code
```

does

```
"bacon/bacon-qr-code": "^1.0"
```

and now I have **v1.0.1** installed which doesn't contain [these changes](https://github.com/Bacon/BaconQrCode/compare/1.0.1...448ee9929aece0e86f0e2b926e636f9b53d03ce1)

**Comment by arteniioleg** [comment]
I changed in `composer.json` the version to `dev-master`

```
"bacon/bacon-qr-code": "dev-master"
```

but it will be safer if you will create releases with stable versions.

**Comment by DASPRiD** [comment]
Released.
