### ISSUE TITLE
find a bug, when i use  ImageMagick draw background image

### ISSUE THREAD

**Issue by yumufeng** [Bacon/BaconQrCode#40]
i'm chinese；
Find a bug, when I use ImageMagick to draw a background image； which would leave stripes between neighboring blocks while drawing QRCode at scale。

**like：**
when i set Fill Opacity

![index](https://user-images.githubusercontent.com/9146937/33950058-52bc8aea-e066-11e7-99d6-8ff19717ec15.png)

**code：**
 
![11](https://user-images.githubusercontent.com/9146937/33950177-b4abcfea-e066-11e7-83a0-3bb307beb4a5.png)

**image：**
![qrcode](https://user-images.githubusercontent.com/9146937/33950244-e6343b4c-e066-11e7-86ea-c90a53c389c2.jpg)

You can refer to this demo:
[https://github.com/sylnsfar/qrcode](https://github.com/sylnsfar/qrcode)

**Comment by DASPRiD** [comment]
This has been fixed in the 2.0 version (to be released).
