### ISSUE TITLE
Multiple QR Sizes on one page

### ISSUE THREAD

**Issue by oppenheimer** [Bacon/BaconQrCode#41]
If you generate multiple QR codes with different sizes on one page, the rect size used in the SVG file defaults to the first QR code on the page.

The problem seems to be the ID is the same ("r0") for each SVG file. 

`<defs><rect id="r0" width="4" height="4" fill="#000001"/></defs>`

I expect my use case is very unusual.
I wasn't able to identify an elegant solution for this issue.  The only idea I had was to add another method which lets you define your own ID which didn't seem very elegant.

**Comment by DASPRiD** [comment]
This is resolved with the new 2.0 version, which is about to be released.
