### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by Sandeeptops** [Bacon/BaconQrCode#45]
Hello,

First  I update composer so Vendor folder create, In that All Package like phpunit,etc...

Then

When I run encodetest file for testing purpose , It throw error Below.

Error:

**Fatal error: Class 'PHPUnit_Framework_TestCase' not found in D:\xampp\htdocs\demo\BaconQrCode-master\tests\BaconQrCode\Encoder\EncoderTest.php on line 22**

![image](https://user-images.githubusercontent.com/35325913/37078384-15efe75c-2205-11e8-8e63-2fc42a37b11b.png)

Can you help me for solve this error.

Thanks&Regards

**Comment by DASPRiD** [comment]
Should be resolved through the rewrite.
