### ISSUE TITLE
Is the image required to exist before you generate the qr code?

### ISSUE THREAD

**Issue by Opendarasa** [Bacon/BaconQrCode#46]
Hi there , 
I tried using your sample code on both an existing image and a non-existing image .
Both case failed , and no image is generated on the latter.
first trial:
`$renderer = new \BaconQrCode\Renderer\Image\Png();
$renderer->setHeight(256);
$renderer->setWidth(256);
$writer = new \BaconQrCode\Writer($renderer);
$writer->writeFile('Hello World!', 'qrcode.png');`

 i then thought i could just write string instead of writing into a file but when i echo i still don't get image 
2nd trial : 

`   
            $renderer = new \BaconQrCode\Renderer\Image\Png();

            $renderer->setHeight(256);

            $renderer->setWidth(256);

            $writer = new \BaconQrCode\Writer($renderer);

            $str= $writer->writeString('Hello World!');
           header('Content-Type:image/png');
          echo $str;`
i get the code below

`�PNG  IHDR�?1IDATx����n�0A'����kP!��؝9��������~������'	�4�&�@�Hi M�	�4�&�@�Hi M�	�4�&�@�Hi M�	�4�&�@�Hi M� �4�&�@�Hi M�	�4����x�^���3:|������u�+W�_u?O��9�p�'��4�&�@�Hi#�W�Z'^��?m=������|�Hi M�	�4�6zpeպ�u�U�럾N?����<Hi M� �4�&Ҏ����@�'i M�	�4�&�@�9�F�� ��<Hi M�	�4�&Ҏ�L[/�v?w�~�?�	@�Hi M�	�4�6z0�|�?�>`�~A�|���!M�	�4�&�@�H�*���}��� M� �4�&�@�H����S_��������w'��	@�Hi M�	�4�6b���u�����Ͽ�I�&�@�Hi M����~_��u�Lx�_<�^�����i M� �4�&�F�V�ǯz��ʴu��s�Us���Y�Q�0�&�@�Hi m�9�������U��w�|J�	�4�&�@�H18�)�ﾾs��0 M�	�4�&�@ڈ9���v���G�>E����̓M@�Hi M� ���\������<�������'i M�	�4�&�@��9�����=��)� �'i M�	�4�&�@ڑs�iv��?��?�'i M�	�4�&�@�9�FO�{�j>P�3x�&�@�Hi M�98e�yչ����_�sw��>��4�&�@�Hi m����kv��OX��F�Hi M�	�4��5y�v� M�	�4�&�@�Hi M�	�4�&�@�Hi M�	�4�&�@�Hi M�	�4�&�@�Hi M� �4�&�@�Hi M�	���mF�sE�}IEND�B`�`

What's the problem ?

**Comment by DASPRiD** [comment]
Are you sure that the process running PHP has write permissions to qrcode.png? Also, do you have error reporting enabled?

**Comment by Opendarasa** [comment]
Yeah the folder is a 775 permission and yes error report is enabled . I’m using Laravel so i ended up switching to simple qr code package to do what i wanted but yeah I’m sure something here and i will certainly find out soon. Thanks

**Comment by DASPRiD** [comment]
Fun fact: that package uses BaconQrCode as its core ;)
