### ISSUE TITLE
The problem of white edge after code generation

### ISSUE THREAD

**Issue by jinzhanyougithub** [Bacon/BaconQrCode#50]
use this address http://www.xxx.com/c/5600876, and add Maring (0) attribute, the result still has white edge. How can I solve it?

This is the way I used it when I was generated: 
QrCode:: format ('png') ->size ($size) ->margin (0) ->generate ('http://www.xxx.com/c/5600876');

There is still a white edge.

**Comment by jinzhanyougithub** [comment]
![Uploading image.png…]()

**Comment by jinzhanyougithub** [comment]
![image](https://user-images.githubusercontent.com/19453557/40471181-6ea7a81c-5f68-11e8-8711-7ef9aa62b40d.png)

**Comment by jinzhanyougithub** [comment]
![image](https://user-images.githubusercontent.com/19453557/40471297-c7bc7982-5f68-11e8-9cf9-eb8e948fa0df.png)

**Comment by jinzhanyougithub** [comment]
I want to scan the two-dimensional code automatically to jump URL.

**Comment by jinzhanyougithub** [comment]
I want to scan the code automatically to jump URL.

**Comment by DASPRiD** [comment]
Are you still on v1 or did you upgrade to v2?

**Comment by DASPRiD** [comment]
Closing since no response for over a year.
