### ISSUE TITLE
Why was the autoloader removed?

### ISSUE THREAD

**Issue by tgelz** [Bacon/BaconQrCode#53]
I was just wondering why the autoloader was removed? I just updated to the latest version and had to map all the classes myself. It's not a big deal, but was there a specific reason for this?

**Comment by DASPRiD** [comment]
Since composer there is no need for a manual written autoloader anymore.

**Comment by tgelz** [comment]
I get that, but not everyone is using composer. A classmap would still be useful in my opinion.

**Comment by DASPRiD** [comment]
Since this library is following PSR-4, there is no need for a classmap. Just register an arbitrary PSR-4 autoloader, maybe even your own.
