### ISSUE TITLE
Can we send bardcode in email

### ISSUE THREAD

**Issue by irfanDC** [Bacon/BaconQrCode#59]
Can we send barcode in email ? I tried but not able to send

**Comment by irfanDC** [comment]
$qrcode = new BaconQrCodeGenerator;
            $barcode = $qrcode->size(500)->generate("Hello e-ticket");

and sending barcode in email message. but empty going

**Comment by DASPRiD** [comment]
I have no idea, which class `BaconQrCodeGenerator` is, that one doesn't exist in this project.
