### ISSUE TITLE
Imagick extention

### ISSUE THREAD

**Issue by GoncaloRod** [Bacon/BaconQrCode#60]
When I try to use BaconQrCode features i get this message `BaconQrCode\Exception\RuntimeException  : You need to install the imagick extension to use this back end` and I have imagick instaled on my homestead

**Comment by alucard18** [comment]
same error for me 

> When I try to use BaconQrCode features i get this message `BaconQrCode\Exception\RuntimeException : You need to install the imagick extension to use this back end` and I have imagick instaled on my homestead

**Comment by alucard18** [comment]
I have the same issue as yours, solved mine by downgrading to version 1.0.3

**Comment by GoncaloRod** [comment]
Downgrading to version 1.0.3 worked! It is not a definitive resolution but, it's fine for the time being.

**Comment by DASPRiD** [comment]
What does this give you?

```bash
php -r 'var_dump(Imagick::getVersion());'
```

**Comment by aFluxx** [comment]
Hello there @DASPRiD ,

I'm the one that made the other ticket, I ran the command as you asked:

```
array(2) {
  ["versionNumber"]=>
  int(1687)
  ["versionString"]=>
  string(66) "ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org"
}
```

That's on homestead.

But I'm wondering, could the issue be related to PHPunit testing, since it runs in :memory:?

**Comment by DASPRiD** [comment]
That shouldn't be related to PHPUnit, Can you also say which PHP version you are using?

**Comment by aFluxx** [comment]
I ran php -v in vagrant (homestead):

```
PHP 7.3.1-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 13 2019 10:19:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.24.3~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

**Comment by aFluxx** [comment]
And when I run it in the CLI of my pc (windows 10);

```
$ php -v
PHP 7.2.10 (cli) (built: Sep 13 2018 01:01:10) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by DASPRiD** [comment]
Do you get the same error on 7.2?

**Comment by aFluxx** [comment]
I'm not really sure.

Yesterday after running composer update I got that same error when I tried to access my website. So I installed imagick on homestead, which solved the issue.

Today I found out that I was getting this error when running phpunit. But I think this runs of php 7.2 which is my own computer (not virtual homestead). Because I do in memory tests.

So yes, same error for php 7.2

**Comment by DASPRiD** [comment]
So in homestead you don't get the error (where imagick is installed), but on your local PC you do get it? Is imagick installed locally?

**Comment by aFluxx** [comment]
Indeed, on homestead no problem with imagick installed.

As far as I'm aware Imagick is not installed locally. I will try this.

**Comment by DASPRiD** [comment]
By the way: the imagick renderer is quite weird at the moment (because of strange path handling in the imagick library). Thus for the moment I'd actually recommend to use the SVG renderer instead. That one also doesn't have any dependencies except the XML library.

**Comment by aFluxx** [comment]
I mainly got here because the package because https://packagist.org/packages/pragmarx/google2fa-laravel uses your package to generate inline QR codes. I will look into if it's possible to use SVG renderer for this purpose! 👍

**Comment by laurencei** [comment]
I got the same issue. From Laravel Homestead using the Google2FA Package.

Let me know what info you need and I'm happy to try to help...

**Comment by DubStepMad** [comment]
@aFluxx @laurencei To fix your issue I downgraded baconqr 
`composer require bacon/bacon-qr-code:~1.0.3`

This works for Laravel 5.8 but not sure how stable it is

**Comment by eldroid-z** [comment]
Any Update on this, i understand the workaround of using version `bacon/bacon-qr-code:~1.0.3`, can we expect a permanent fix for the new version?

**Comment by DASPRiD** [comment]
> Any Update on this, i understand the workaround of using version `bacon/bacon-qr-code:~1.0.3`, can we expect a permanent fix for the new version?

This is not an issue with this package, but not having Imagick properly installed. So the solution is to install that extension or use the SVG renderer (which is the preferred method anyway).

**Comment by eldroid-z** [comment]
Thanks for your reply,

@DASPRiD  Can you explain a bit more, so i can try to solve it.

1. if not installed properly, why is it working when we target a lower version.
2. Is there anything that we can check / checklist of packages that are need to be installed to make this work. because now i couldn't figure out what causing the failure with the newer version.

We'll also look into SVG renderer.

Any help is highly appreciated, Thanks.

**Comment by DASPRiD** [comment]
@eldroid-z Version 1 used GDLib for rendering, while version 2 uses Imagick, due to the now required vector feature set.

There's a problem with Imagick right now though (it has a broken coordinate system, which results in artefacts, most noticeable on low res QR-codes. That's another reason why I'd recommend to use the SVG renderer instead.

If there's a good reason why you couldn't use SVGs, in order to use the Imagick renderer you have to install the extension, e.g. on Debian-based systems by calling `apt install php-imagick`.

**Comment by PaddyLock** [comment]
Why is this issue still open? I get this error with version 3 and version 4. But according to packagist ext-imagick is only a suggests, not a required. So why does it break? I have both GD and imagick extensions installed with php 7.3.8

**Comment by davegcc** [comment]
I recently upgraded to PHP 8 (without Imagick), and had to switch to the SVG version, but it's is working great.

use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;

function doStuff()
{
        $writer = new Writer(
            new ImageRenderer(
                new RendererStyle(200),
                new SvgImageBackEnd()
            )
        );
        return $writer->writeString($g2faUrl);
}

**Comment by duolabmeng6** [comment]
What is the solution? Why did I encounter this problem

**Comment by duolabmeng6** [comment]
# Solution It is running well and has been tested

composer require bacon/bacon-qr-code:~1.0.3

```
$renderer = new \BaconQrCode\Renderer\Image\Png();
$renderer->setHeight(256);
$renderer->setWidth(256);
$writer = new \BaconQrCode\Writer($renderer);
$writer->writeString('Hello World!');
```

**Comment by icatpojan** [comment]
buat yang tulisanya suruh istall ekstensi imagick, downgrade aja librarynya ke versi 1

**Comment by DASPRiD** [comment]
Closing as this is was resolved downstream.

**Comment by mustanggb** [comment]
> Closing as this is was resolved downstream.

@DASPRiD I presume you're referring to the broken coordinate system and/or artefacts you mentioned earlier, any chance you know which commit resolved this?

https://github.com/Imagick/imagick

**Comment by DASPRiD** [comment]
> @DASPRiD I presume you're referring to the broken coordinate system and/or artefacts you mentioned earlier, any chance you know which commit resolved this?

I was referring to the downstream project using the SVG renderer. The coordinate system is still broken in Imagick IIRC.
