### ISSUE TITLE
Extendability

### ISSUE THREAD

**Issue by rjvandoesburg** [Bacon/BaconQrCode#62]
Hello,

So my customer wanted the left top eye to be a specific color like so:
![Screenshot 2019-05-28 at 08 06 54](https://user-images.githubusercontent.com/1488300/58454723-9da02c00-811f-11e9-828c-5c5e95737c96.png)
Now this was made possible using this package (yay)

However, achieving this was not as easy as I thought.
`BaconQrCode\Renderer\RendererStyle\Fill` has a constructor where you can specify every aspect of the code, however you made the constructor private for some reason which meant I had to extend, which is not possible because you made the class Final.
I made my own class, but then I had to extend `BaconQrCode\Renderer\RendererStyle\RendererStyle` because that constructor is public and uses interfaces, except for the Fill class. But alas `RendereStyle` is also final so I had to copy that class as well

Almost there, I also had to extend `BaconQrCode\Renderer\ImageRenderer` because it referenced `RendererStyle`, but also because of final I had to copy the entire class again.

What I am getting at is, are you open for a Pull Request that opens up the library for extensions build on top? e.g. making methods public/protected, make the classes extendable (no more final), and use interfaces for everything.

Because this is a little time consuming I figured I'd ask first if I could assist you with this or if I should create my own fork to implement changes I could use. (with no intention of PR)

Thanks for this package, it has helped me a lot.

Cheers,
RJ

**Comment by DASPRiD** [comment]
The reason the constructor is private is because there are a number of named constructors (static methods) to create the renderer style. You are likely interested in using the `withForegroundColor()` named constructor.

**Comment by rjvandoesburg** [comment]
Hmm, don't know how I managed to miss that one, cheers!

But my point still stands as to make the package more open to extensibility :)

**Comment by DASPRiD** [comment]
Usually composition should be preferred over inheritance. In the case of the RendererStyle, extendibility actually makes no sense, because it's a value object with very specific content. Other objects in BQRC actually do have interfaces where it makes sense to extend.
