### ISSUE TITLE
Open for PR for a GD renderer?

### ISSUE THREAD

**Issue by willemstuursma** [Bacon/BaconQrCode#67]
Hi,

I see lots of unanswered issues and pull requests so I wanted to check before investing a lot of time.

Are you open to accepting a PR that will add a GD based renderer?

**Comment by DASPRiD** [comment]
If it'd support all features of the other renderers, then yes.

**Comment by willemstuursma** [comment]
The renderers are pretty complex looking into it. I was expecting a method that would be given a size and an array of zeroes and ones for each block of the QR code. 

This eliptic arcs and paths, why is that even there? I see that it is used by DotsModule and RoundnessModule, but thinking of QR codes it does not make immediate sense.

**Comment by DASPRiD** [comment]
Well, this library allows for creating styled QR codes.So all the renderers get are drawing paths to follow.

**Comment by DASPRiD** [comment]
No updated on this for several months, closing. Feel free to open a PR if you want to.
