### ISSUE TITLE
Trying to make OTP QR

### ISSUE THREAD

**Issue by abmmhasan** [Bacon/BaconQrCode#75]
This Generating QR of type 'TEXT', how to make it of 'url' type?

**Comment by matedon** [comment]
All the data are plain text in qr code. So that depends on your purpose.
I think you have to just simply put http:// or https:// on the start of your string.
You are also able to use schemas look arround here:
https://www.webfx.com/blog/web-design/qr-codes-uri-schemes/

**Comment by abmmhasan** [comment]
![image](https://user-images.githubusercontent.com/7711128/94156531-02010600-fea2-11ea-8b36-2c6e6e44fe30.png)
Barcode Scanner detects it as Text type where if I use that in Google QR it is of url type. This is not about schema I think. There is some other kind of parameter/encoding type have to be passed!

**Comment by DASPRiD** [comment]
Your QRCode string is URL encoded. You should decode it first before generating your QR code.

**Comment by abmmhasan** [comment]
Thanks, that did the trick!
