### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by ZeNiRe** [Bacon/BaconQrCode#80]
Has anyone verified support for PHP 8 already?

**Comment by yosirn** [comment]
no does not support php 8

**Comment by maarten-mald-digital** [comment]
Yes please : (

**Comment by Skayo** [comment]
It doesn't work in PHP 8 with JIT/Opcache enabled for some reason.
But just adding `ini_set('opcache.enable', '0');` before doing any QR-Code stuff works for me.

**Comment by vstyler96** [comment]
Hello! I know this is probably oudated, but actually this package is supported by PHP 8. You just need to have **ext-iconv** enabled.

**Comment by ZeNiRe** [comment]
Thank you for confirming!
