### ISSUE TITLE
Question: Does this library handle creation of WIFI access QR codes?

### ISSUE THREAD

**Issue by inglesuniversal** [Bacon/BaconQrCode#85]
thanks

**Comment by joeworkman** [comment]
I reverse decoded my guest wifi QR code. this is the format that is used to create it... 

```
WIFI:S:{{Network SSID}};T:WPA;P:{{PASSCODE}};;
```

Substitute the mustache vars in there with the actual values for your network. Hope that this helps.

**Comment by inglesuniversal** [comment]
It worked like a charm. Thanks so much for contributing with my long awaited and over-searched request!
