### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by joeworkman** [Bacon/BaconQrCode#90]
Does anyone know if it's possible to add a logo or text in the middle of the QR code? Preferably using the SVG plugin.

**Comment by DASPRiD** [comment]
The easiest thing would be to simply run the resulting SVG code through an SVG library and simply overlay a logo or text with a white background on top of the QR code (making sure to not cover too much data points).

**Comment by joeworkman** [comment]
I'm a QR noob... I assumed that you could not cover any of it at all.

**Comment by DASPRiD** [comment]
No, QR codes contain error correction data. The amount of redundant data depends on the selected error correction level. The highest level (H) can sustain a loss of up to 30%.
