### ISSUE TITLE
Error in PHP 8.

### ISSUE THREAD

**Issue by zeus0219** [Bacon/BaconQrCode#96]
![image](https://user-images.githubusercontent.com/88533539/140555769-60cf87be-564e-4fb7-91de-3d2874cb7bb3.png)
I am getting this error when I upgrade my php version to 8.

**Comment by DASPRiD** [comment]
It is telling you that you need to install (and enable) the imagick extension.

**Comment by topcoder1208** [comment]
No, I installed Imagick extension but still got error.

**Comment by DASPRiD** [comment]
Must be your something with your system configuration, works here and on the test servers.
